server:
  port: 6677
spring:
  application:
    name: treasure-console
  datasource:
    url: jdbc:h2:mem:treasure
    username: treasure
    password: qiqiang
  mvc:
    static-path-pattern: /front-web
treasure:
  nginx:
    protocol: https
    serverName: www.qiqiang.online
    listener: 443
    location:
      path: /blog
      root: /data/hexo
  command:
    work-dir: /data/hexo/blog
    commands:
      - id: 1
        command: ls -l
        work-dir: /data/hexo/blog
      - id: 2
        command: hexo g
        work-dir: /data/hexo/blog
      - id: 3
        command: git pull
        work-dir: /data/hexo/blog
forest:
  log:
    enable: true
    package-path: online.qiqiang.treasure.console.controller
    ignore-resp: context
    ignore-text: '#忽略该字段#'
