server:
  port: 6677
spring:
  application:
    name: treasure-console
  mvc:
    static-path-pattern: /front-web
forest:
  log:
    enable: true
    package-path: online.qiqiang.treasure.console.controller
    ignore-resp: context
    ignore-text: '#忽略该字段#'
treasure:
  nginx:
    protocol: https
    serverName: www.qiqiang.online
    listener: 443
    location:
      path: /blog
      root: /data/hexo
  command:
    work-dir: /data/hexo/blog
    password: 520qq
    commands:
      - id: 1
        command: ls -l
        work-dir: /data/hexo/blog
        description: 列出文件
      - id: 2
        command: git pull
        work-dir: /data/hexo/blog
        open: false
        description: 拉取 hexo 代码
      - id: 3
        command: hexo g
        work-dir: /data/hexo/blog
        open: false
        description: 生成 hexo public 文件
      - id: 4
        command: 3,2
        type: pipeline
        description: 一键发布最新 hexo